### ISSUE TITLE
The default address for the protocape is "0x57" not  "0x54"

### ISSUE THREAD

**Issue by JasonLS** [jadonk/beagle-tester#19]
https://github.com/jadonk/beagle-tester/blob/f4441c71f8664c8d0e29528a8715fe4f553d1eec/beagle-tester.c#L3521

the problem was that the address would be 54 if all of the 6 EEPROM headers were bridged together, GHI wanted to change the protoboard to have no headers at all

**Comment by jadonk** [comment]
https://github.com/jadonk/beagle-tester/commit/296e2da8a9ac8d87c7904f3a5f9ba942bb68d5c8
